language: csharp
solution: src/INIFileParser.sln
before_install:
  - git config --global url."https://github.com/".insteadOf "git@github.com:"
install:
  - dotnet restore src/INIFileParser.sln
script:
  - msbuild src/INIFileParser.sln /nologo /verbosity:normal /p:Configuration=Release
  - dotnet test src/IniFileParser.Tests/INIFileParser.Tests.csproj --no-build
mono:
  - latest
  - 3.12.0
dotnet:
  - 2.1.3